#! /bin/bash
set -e




LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/lib64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/user/lib64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/user/lib64/mono
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/usr/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/user/lib/gtk-sharp-2.0
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/user/lib/mono/gtk-sharp-2.0
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/user/lib/mono


export LD_LIBRARY_PATH

cd ${HOME}

exec ${APPDIR}/usr/bin/mono-sgen --config ${APPDIR}/etc/mono/config ${APPDIR}/lib/pinta/Pinta.exe "$@"
